filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'
        - 'src/AppBundle/Tests/*'

tools:
    php_cs_fixer:
        config:
            level: symfony
            fixers: { short_array_syntax: true }

build_failure_conditions:
    - 'issues.label("coding-style").new.exists'
