sudo: required

services:
  - docker

install:
  - make

script:
  - make start
  - make console security:check
  - make console doctrine:schema:create
  - make test
  - docker-compose run --rm app /usr/bin/php vendor/bin/php-cs-fixer fix --config=.php_cs -v --dry-run --using-cache=no --path-mode=intersection `git diff --name-only --diff-filter=ACMRTUXB $TRAVIS_COMMIT_RANGE`

notifications:
  email: false
