language: php

sudo: false

cache:
  directories:
    - bin
    - vendor
    - $HOME/.composer/cache

php:
  - 7.0

env:
  - SYMFONY_PHPUNIT_VERSION=5.5

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - composer install --prefer-dist --no-interaction --no-progress

script:
  - vendor/bin/simple-phpunit
  - vendor/bin/php-cs-fixer fix --config=.php_cs -v --dry-run --using-cache=no --path-mode=intersection `git diff --name-only --diff-filter=ACMRTUXB $TRAVIS_COMMIT_RANGE`

notifications:
  email: false
